interface ZIF_I_00_CONNECTIONTP_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZI_00_CONNECTIONTP,
 CREATE_ZI_00_CONNECTIONTP      TYPE /BOBF/ACT_KEY VALUE '005056044E851EED9080892669EA23E6',
 DELETE_ZI_00_CONNECTIONTP      TYPE /BOBF/ACT_KEY VALUE '005056044E851EED9080892669EAA3E6',
 LOCK_ZI_00_CONNECTIONTP        TYPE /BOBF/ACT_KEY VALUE '005056044E851EED9080892669E963E6',
 SAVE_ZI_00_CONNECTIONTP        TYPE /BOBF/ACT_KEY VALUE '005056044E851EED9080892669EB23E6',
 SWITCH_PLANETYPE               TYPE /BOBF/ACT_KEY VALUE '005056044E851EDD909407566B097201',
 UNLOCK_ZI_00_CONNECTIONTP      TYPE /BOBF/ACT_KEY VALUE '005056044E851EED9080892669E9A3E6',
 UPDATE_ZI_00_CONNECTIONTP      TYPE /BOBF/ACT_KEY VALUE '005056044E851EED9080892669EA63E6',
 VALIDATE_ZI_00_CONNECTIONTP    TYPE /BOBF/ACT_KEY VALUE '005056044E851EED9080892669EAE3E6',
      END OF ZI_00_CONNECTIONTP,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZI_00_CONNECTIONTP,
        BEGIN OF LOCK_ZI_00_CONNECTIONTP,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_ZI_00_CONNECTIONTP,
        BEGIN OF UNLOCK_ZI_00_CONNECTIONTP,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_ZI_00_CONNECTIONTP,
      END OF ZI_00_CONNECTIONTP,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZI_00_CONNECTIONTP,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE '005056044E851EED9080894DAC6B83EB',
      END OF ZI_00_CONNECTIONTP,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZI_00_CONNECTIONTP,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EED9080892669E943E6',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EED9080892669E903E6',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EED9080892669EA03E6',
      END OF ZI_00_CONNECTIONTP,
      BEGIN OF ZI_00_CONNECTIONTP_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EED9080892669EB83E6',
      END OF ZI_00_CONNECTIONTP_LOCK,
      BEGIN OF ZI_00_CONNECTIONTP_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EED9080892669EB63E6',
      END OF ZI_00_CONNECTIONTP_MESSAGE,
      BEGIN OF ZI_00_CONNECTIONTP_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EED9080892669EBA3E6',
      END OF ZI_00_CONNECTIONTP_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZI_00_CONNECTIONTP,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZI_00_CONNECTIONTP,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '005056044E851EED9080892669E863E6' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZI_00_CONNECTIONTP' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZI_00_CONNECTIONTP,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE '005056044E851EED9080894DAC6BA3EB',
      END OF ZI_00_CONNECTIONTP,
    END OF SC_DETERMINATION .
  constants:
    BEGIN OF SC_GROUP,
 ZI_00_CONNECTIONTP             TYPE /BOBF/OBM_GROUP_KEY VALUE '005056044E851EED9080894DAC7363EB',
    END OF SC_GROUP .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZI_00_CONNECTIONTP             TYPE /BOBF/OBM_NODE_KEY VALUE '005056044E851EED9080892669E8A3E6',
 ZI_00_CONNECTIONTP_LOCK        TYPE /BOBF/OBM_NODE_KEY VALUE '005056044E851EED9080892669E923E6',
 ZI_00_CONNECTIONTP_MESSAGE     TYPE /BOBF/OBM_NODE_KEY VALUE '005056044E851EED9080892669E8E3E6',
 ZI_00_CONNECTIONTP_PROPERTY    TYPE /BOBF/OBM_NODE_KEY VALUE '005056044E851EED9080892669E9E3E6',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZI_00_CONNECTIONTP,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  CARRIERID                      TYPE STRING VALUE 'CARRIERID',
  CONNECTIONID                   TYPE STRING VALUE 'CONNECTIONID',
  COUNTRYFROM                    TYPE STRING VALUE 'COUNTRYFROM',
  CITYFROM                       TYPE STRING VALUE 'CITYFROM',
  AIRPORTFROM                    TYPE STRING VALUE 'AIRPORTFROM',
  COUNTRYTO                      TYPE STRING VALUE 'COUNTRYTO',
  CITYTO                         TYPE STRING VALUE 'CITYTO',
  AIRPORTTO                      TYPE STRING VALUE 'AIRPORTTO',
  DEPARTURETIME                  TYPE STRING VALUE 'DEPARTURETIME',
  ARRIVALTIME                    TYPE STRING VALUE 'ARRIVALTIME',
  DISTANCE                       TYPE STRING VALUE 'DISTANCE',
  DISTANCEUNIT                   TYPE STRING VALUE 'DISTANCEUNIT',
  FLIGHTTYPE                     TYPE STRING VALUE 'FLIGHTTYPE',
  PERIOD                         TYPE STRING VALUE 'PERIOD',
      END OF ZI_00_CONNECTIONTP,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZI_00_CONNECTIONTP,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '005056044E851EED9080892669E8C3E6',
      END OF ZI_00_CONNECTIONTP,
    END OF SC_NODE_CATEGORY .
  constants:
    BEGIN OF SC_VALIDATION,
      BEGIN OF ZI_00_CONNECTIONTP,
 ALTKEY_UNIQUENESS_CHECK        TYPE /BOBF/VAL_KEY VALUE '005056044E851EED9080894DAC6C03EB',
 MANDATORY_FIELDS               TYPE /BOBF/VAL_KEY VALUE '005056044E851EED90974B91DDB639FC',
      END OF ZI_00_CONNECTIONTP,
    END OF SC_VALIDATION .
endinterface.
